.PHONY: clean All

All:
	@echo "----------Building project:[ SudokuRedux - Debug ]----------"
	@$(MAKE) -f  "SudokuRedux.mk"
clean:
	@echo "----------Cleaning project:[ SudokuRedux - Debug ]----------"
	@$(MAKE) -f  "SudokuRedux.mk" clean
